{
 "title": "Model Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Model Performance Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "model_metrics",
     "query": "SELECT mean(\"accuracy\") AS \"Accuracy\", mean(\"precision\") AS \"Precision\", mean(\"recall\") AS \"Recall\", mean(\"f1\") AS \"F1\" FROM \"autogen\".\"model_metrics\" WHERE $timeFilter GROUP BY time(30s) fill(previous)",
     "select": [
      [
       { "params": [ "accuracy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Accuracy" ], "type": "alias" }
      ],
      [
       { "params": [ "precision" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Precision" ], "type": "alias" }
      ],
      [
       { "params": [ "recall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Recall" ], "type": "alias" }
      ],
      [
       { "params": [ "f1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "F1" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outlier Counter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outlier",
     "query": "SELECT sum(\"is_outlier\") FROM \"outlier\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "is_outlier" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Concept Drift Counter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "concept-drift",
     "query": "SELECT sum(\"is_concept_drift\") FROM \"concept-drift\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "is_concept_drift" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Accuracy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model_metrics",
     "query": "SELECT last(\"accuracy\") FROM \"model_metrics\"",
     "select": [
      [
       { "params": [ "accuracy" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Precision",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model_metrics",
     "query": "SELECT last(\"precision\") FROM \"model_metrics\"",
     "select": [
      [
       { "params": [ "accuracy" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Recall",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model_metrics",
     "query": "SELECT last(\"recall\") FROM \"model_metrics\"",
     "select": [
      [
       { "params": [ "accuracy" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall F1",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model_metrics",
     "query": "SELECT last(\"f1\") FROM \"model_metrics\"",
     "select": [
      [
       { "params": [ "accuracy" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  }
 ]
}